apiVersion: apps/v1
kind: Deployment
metadata:
  name: comm-control

spec:
  replicas: 1
  selector:
    matchLabels:
      app: comm-control
  template:
    metadata:
      labels:
        app: comm-control
    spec:
      containers:
        - name: comm-control
          image: devopslabsreg.azurecr.io/commcontrol:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              memory: "128Mi"
              cpu: "10m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: Redis__ConnectionString
              value: redis:6379
            - name: BasePath
              value: /control
