apiVersion: apps/v1
kind: Deployment
metadata:
  name: mapclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mapclient
  template:
    metadata:
      labels:
        app: mapclient
    spec:
      containers:
        - name: mapclient
          image: devopslabsreg.azurecr.io/mapclient:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: config-volume
              mountPath: /app/src/config/config.json
              subPath: config.json
          resources:
            requests:
              memory: "128Mi"
              cpu: "10m"
            limits:
              memory: "256Mi"
              cpu: "250m"
      volumes:
        - name: config-volume
          configMap:
            name: mapclient-config
