apiVersion: apps/v1
kind: Deployment
metadata:
  name: hivemind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hivemind
  template:
    metadata:
      labels:
        app: hivemind
    spec:
      containers:
        - name: hivemind
          image: devopslabsreg.azurecr.io/hivemind-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5149
          resources:
            requests:
              memory: "128Mi"
              cpu: "10m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: CommunicationConfiguration__CommunicationControlIP
              value: comm-control
            - name: CommunicationConfiguration__CommunicationControlPath
              value: control/api/v1/hive
            - name: CommunicationConfiguration__CommunicationControlPort
              value: "80"
