name: Build & Deploy CommunicationControl to Azure

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/CommunicationControl

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and Push Docker image to ACR
        run: |
          BRANCH_NAME=${{ github.head_ref || github.ref_name }}
          ENV_TAG=$([[ "$BRANCH_NAME" == "main" ]] && echo "prod" || echo "dev")
          IMAGE_TAG=$ENV_TAG-${GITHUB_SHA}
          ACR_NAME=${{ secrets.ACR_NAME }}

          az acr login --name $ACR_NAME

          docker build -t $ACR_NAME.azurecr.io/commcontrol:$IMAGE_TAG .
          docker push $ACR_NAME.azurecr.io/commcontrol:$IMAGE_TAG

      - name: Set environment variables for AKS
        run: |
          BRANCH_NAME="${{ github.head_ref || github.ref_name }}"
          if [ "$BRANCH_NAME" = "main" ]; then
            echo "AKS_RG=${{ secrets.AKS_RG }}" >> $GITHUB_ENV
            echo "AKS_CLUSTER=${{ secrets.AKS_CLUSTER }}" >> $GITHUB_ENV
          else
            echo "AKS_RG=${{ secrets.AKS_RG_DEV }}" >> $GITHUB_ENV
            echo "AKS_CLUSTER=${{ secrets.AKS_CLUSTER_DEV }}" >> $GITHUB_ENV
          fi

      - name: Set up kubectl
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.AKS_RG }}
          cluster-name: ${{ env.AKS_CLUSTER }}

      - name: Deploy to AKS
        run: |
          ENV_TAG=$([[ "${GITHUB_REF##*/}" == "main" ]] && echo "prod" || echo "dev")
          IMAGE_TAG=$ENV_TAG-${GITHUB_SHA}
          ACR_NAME=${{ secrets.ACR_NAME }}

          kubectl set image deployment/comm-control comm-control=$ACR_NAME.azurecr.io/commcontrol:$IMAGE_TAG -n default